
#logba#logback对接logstash的日志配置文件
logging:
  config: classpath:logback-spring.xml
#elasticsearch相关配置
##es的cluster集群名称可以查看服务器安装的集群名称 curl http://192.168.199.196:9200 获取到集群名称
#spring.data.elasticsearch: cluster-name=docker-cluster
##注意端口为9300  9300 是 Java 客户端的端口,支持集群之间的通信。9200 是支持 Restful HTTP 的接口
#spring.data.elasticsearch.cluster-nodes=192.168.199.196:9300
es:
  url: http://192.168.199.196:9300
